/**
 * services/reports/reportsService.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Pure API service for the Reports Center.
 * Handles all HTTP calls; the store calls these methods and owns state.
 * Keeps the data-fetching layer decoupled from React and the store.
 */

import { request } from '../../api/request';
import { Endpoints } from '../../api/endpoints';
import type { ReportRow, GenerateReportRequest } from '../../types/reports';

// ─── Response shapes ──────────────────────────────────────────────────────────

export interface ListReportsResponse {
  reports: ReportRow[];
}

// ─── Service ──────────────────────────────────────────────────────────────────

export const reportsService = {
  /**
   * Fetch the report list for a project.
   */
  async listReports(projectId: string): Promise<ReportRow[]> {
    const res = await request.get<ListReportsResponse>(
      Endpoints.projects.reports.list(projectId),
    );
    return res.reports ?? [];
  },

  /**
   * Generate a new report and return the raw Response so the caller
   * can stream or blob the PDF payload.
   */
  async generateReport(
    projectId: string,
    payload: GenerateReportRequest,
  ): Promise<Response> {
    const res = await fetch(Endpoints.projects.reports.generate(projectId), {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });
    return res;
  },

  /**
   * Trigger a PDF download for an existing report by re-generating it.
   * Returns { blobUrl, filename }.
   */
  async downloadReportPdf(
    projectId: string,
    payload: GenerateReportRequest,
  ): Promise<{ blobUrl: string; filename: string }> {
    const res = await this.generateReport(projectId, payload);

    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      const msg = (data as { error?: string }).error ?? 'Failed to generate report';
      throw new Error(msg);
    }

    const blob = await res.blob();
    const blobUrl = URL.createObjectURL(blob);
    const cd = res.headers.get('Content-Disposition') ?? '';
    const match = cd.match(/filename="([^"]+)"/);
    const filename = match?.[1] ?? 'report.pdf';

    return { blobUrl, filename };
  },

  /**
   * Build a Markdown string from a report row (client-side export).
   */
  buildMarkdown(report: ReportRow): string {
    return [
      `# ${report.title}`,
      '',
      `**Risk Level:** ${report.riskLevel}`,
      `**Generated By:** ${report.generatedBy}`,
      `**Generated At:** ${new Date(report.createdAt).toLocaleString()}`,
      '',
      '## Sections Included',
      '',
      ...report.sections.map((s) => `- ${s}`),
      '',
      '---',
      '',
      '*Full AI-generated content is available in the PDF export.*',
    ].join('\n');
  },

  /**
   * Build a JSON export string from a report row.
   */
  buildJson(report: ReportRow): string {
    return JSON.stringify(report, null, 2);
  },

  /**
   * Trigger a browser download for the given blob URL / filename.
   */
  triggerDownload(url: string, filename: string): void {
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = filename;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    setTimeout(() => URL.revokeObjectURL(url), 60_000);
  },
};
